[workspace]
members = [
    "programs/iat_b3_consensus",
    "programs/iat_b3_economy",
    "programs/iat_b3_law",
    "programs/iat_b3_vault",
    "programs/iat_v2",
]
resolver = "2"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
