"use client";

import { useEffect, useState } from "react";
import { LaunchClock } from "../LaunchClock";
import "./launch.css";

const copy = {
  en: {
    dossier: "WHITE DOSSIER", eyebrow: "STAR ASCENT // GENESIS CONTROL", title: <>THE ROOM<br />IS OPEN.</>, lede: "One signal. One public record. No shadow links.", actions: ["OPEN OFFICIAL SIGNAL DIRECTORY", "OPEN PROOF BOARD", "OPEN FIELD GUIDE", "OPEN PRESS ROOM", "READ THE DOSSIER", "REVIEW OPEN-SOURCE CODE"], status: "PUBLIC STATUS // UTC",
    cards: [["BROADCAST", "29 JUL // 15:00:00 UTC", "The open-source ceremony window begins at this exact time."], ["GENESIS", "SCHEDULED // EVIDENCE HOLD", "The window is public; transaction execution still requires physical Model T confirmation and passing evidence gates."], ["CHAIN RECORD", "HOLD // AWAITING EVIDENCE", "No mint, authority, allocation, or claim fact is published before direct proof."], ["SOURCE", "PUBLIC // MIT", "Review the exact transaction builder, configuration interlock, and validation scripts before the window opens."]],
    runTitle: "EVIDENCE ORDER", moments: [["15:00:00 UTC", "OPEN THE WINDOW", "Open the broadcast and the public source record. A timer never signs or submits a transaction."], ["DEVNET FIRST", "MODEL T REHEARSAL", "Run the exact four-transaction ceremony with a separate physical confirmation for each devnet transaction."], ["AFTER ALL GATES", "MAINNET DECISION", "Proceed only if the independent verifier confirms metadata, destinations, locks, digests, and the complete rehearsal."], ["AFTER EVIDENCE", "PUBLISH THE RECORD", "Any mint, authority, allocation, or route is meaningful only once direct public evidence is linked."]],
    real: "WHAT MAKES IT REAL", realTitle: "Five proofs. One public record.", proofs: ["Mint address on the site and broadcast screen.", "Exact supply and token program.", "Mint and freeze authority evidence.", "Allocation wallets and time-lock records.", "A matching record across every official surface."], gate: "THE OPERATOR GATE", gateTitle: "ONE DEVICE. ONE VERIFIER. ONE PUBLIC RECORD.", operators: [["01 // SIGNER", "CONFIRM\nPHYSICALLY.", "The signing device shows the details. The signer reviews what is on-device and confirms only the intended action."], ["02 // VERIFIER", "CHECK\nINDEPENDENTLY.", "The verifier matches the public address, supply, program, and authority state against the evidence record."], ["03 // PUBLISHER", "MAKE THE\nRECORD REAL.", "The public site changes only after the evidence is ready to be checked by anyone else."]], manifest: "READ THE MINT MANIFEST", rule: "THE ONLY RULE", ruleText: "If it is not published here, in the Dossier, and on the broadcast screen, it is not official.", terminal: "OPEN ACTIVATION TERMINAL", footer: "INTERNAL AGENCY // STAR ASCENT // BUILD IN PUBLIC",
  },
  tr: {
    dossier: "BEYAZ DOSYA", eyebrow: "STAR ASCENT // BAŞLANGIÇ KONTROLÜ", title: <>ODA<br />AÇIK.</>, lede: "Tek sinyal. Tek kamu kaydı. Gizli bağlantı yok.", actions: ["RESMÎ SİNYAL DİZİNİNİ AÇ", "KANIT PANOSUNU AÇ", "SAHA REHBERİNİ AÇ", "BASIN ODASINI AÇ", "DOSYAYI OKU", "AÇIK KAYNAK KODU İNCELE"], status: "KAMU DURUMU // İSTANBUL",
    cards: [["YAYIN", "29 TEM // 18:00:00 İSTANBUL", "Açık kaynak tören penceresi bu tam zamanda başlar."], ["BAŞLANGIÇ", "PLANLI // KANIT BEKLET", "Pencere kamusaldır; işlem yürütme fiziksel Model T onayı ve geçen kanıt eşikleri gerektirir."], ["ZİNCİR KAYDI", "BEKLET // KANIT BEKLİYOR", "Doğrudan kanıt olmadan mint, yetki, tahsis veya claim bilgisi yayımlanmaz."], ["KAYNAK", "KAMUYA AÇIK // MIT", "Pencere açılmadan önce işlem kurucuyu, yapılandırma kilidini ve doğrulama betiklerini incele."]],
    runTitle: "KANIT SIRASI", moments: [["18:00:00 İSTANBUL", "PENCEREYİ AÇ", "Yayını ve kamuya açık kaynak kaydını aç. Zamanlayıcı işlem imzalamaz veya göndermez."], ["ÖNCE DEVNET", "MODEL T PROVASI", "Her devnet işlemi için ayrı fiziksel onayla dört işlemli töreni yürüt."], ["TÜM EŞİKLERDEN SONRA", "MAINNET KARARI", "Yalnızca bağımsız doğrulayıcı metadata, hedefler, kilitler, özetler ve tam provayı doğrularsa ilerle."], ["KANITTAN SONRA", "KAYDI YAYIMLA", "Mint, yetki, tahsis veya rota yalnızca doğrudan kamu kanıtı bağlandığında anlamlıdır."]],
    real: "ONU GERÇEK YAPAN", realTitle: "Beş kanıt. Tek kamu kaydı.", proofs: ["Sitede ve yayın ekranında mint adresi.", "Kesin arz ve token programı.", "Mint ve freeze yetkisi kanıtı.", "Tahsis cüzdanları ve zaman kilidi kayıtları.", "Her resmî yüzeyde eşleşen kayıt."], gate: "OPERATÖR KAPISI", gateTitle: "TEK CİHAZ. TEK DOĞRULAYICI. TEK KAMU KAYDI.", operators: [["01 // İMZACI", "FİZİKSEL\nONAY.", "İmza cihazı ayrıntıları gösterir. İmzacı cihazda gördüğünü inceler ve yalnızca amaçlanan işlemi onaylar."], ["02 // DOĞRULAYICI", "BAĞIMSIZ\nKONTROL.", "Doğrulayıcı kamu adresini, arzı, programı ve yetki durumunu kanıt kaydıyla eşleştirir."], ["03 // YAYIMCI", "KAYDI\nGERÇEK KIL.", "Kamu sitesi yalnızca kanıt herkes tarafından kontrol edilebilir olduğunda değişir."]], manifest: "MINT MANİFESTOSUNU OKU", rule: "TEK KURAL", ruleText: "Burada, Dosyada ve yayın ekranında yayımlanmıyorsa resmî değildir.", terminal: "AKTİVASYON TERMİNALİNİ AÇ", footer: "INTERNAL AGENCY // STAR ASCENT // AÇIKTA İNŞA",
  },
};

export default function LaunchPage() {
  const [language, setLanguage] = useState<"en" | "tr">("en");
  useEffect(() => { if (window.location.hostname.includes("ileriakil")) setLanguage("tr"); }, []);
  const t = copy[language];
  return <main className="launch-page"><div className="launch-page-stars" aria-hidden="true" /><nav><a href="/">IA<span>///</span></a><a href="/dossier">{t.dossier} ↗</a></nav>
    <section className="launch-page-hero"><p>{t.eyebrow}</p><h1>{t.title}</h1><span>{t.lede}</span><LaunchClock language={language} /><div className="launch-page-actions"><a href="/signal">{t.actions[0]} ↗</a><a href="/proof">{t.actions[1]} ↗</a><a href="/verify">{t.actions[2]} ↗</a><a href="/press">{t.actions[3]} ↗</a><a href="/dossier">{t.actions[4]} ↗</a><a href="https://github.com/InternalAgencyIO/InternalAgency/tree/agent/iat-launch-window/projects/star-ascent/site" target="_blank" rel="noreferrer">{t.actions[5]} ↗</a></div></section>
    <section className="launch-status" aria-label={t.status}><p>{t.status}</p><div>{t.cards.map(([label, state, note], index) => <article key={label}><span>0{index + 1}</span><strong>{label}</strong><b>{state}</b><small>{note}</small></article>)}</div></section>
    <section className="launch-rewards-entry"><p>{language === "en" ? "NODE REWARDS // GENESIS GIFT" : "DÜĞÜM ÖDÜLLERİ // BAŞLANGIÇ HEDİYESİ"}</p><h2>{language === "en" ? <>100 IAT.<br />THE FIRST 1,000.</> : <>100 IAT.<br />İLK 1.000.</>}</h2><span>{language === "en" ? "The public claim system remains on HOLD until verified Genesis evidence and node-binding gates are live." : "Kamu claim sistemi, doğrulanmış Başlangıç kanıtı ve düğüm bağlama eşikleri canlı olana kadar BEKLET durumundadır."}</span><a href="/rewards">{language === "en" ? "OPEN NODE REWARDS" : "DÜĞÜM ÖDÜLLERİNİ AÇ"} ↗</a></section>
    <section className="launch-run"><p>{t.runTitle}</p><div>{t.moments.map(([time,title,body],i)=><article key={time}><span>0{i+1}</span><time>{time}</time><h2>{title}</h2><p>{body}</p></article>)}</div></section>
    <section className="launch-evidence"><p>{t.real}</p><h2>{t.realTitle}</h2><div>{t.proofs.map((item,index)=><article key={item}><span>0{index + 1}</span><p>{item}</p></article>)}</div></section>
    <section className="launch-operators"><p>{t.gate}</p><h2>{t.gateTitle}</h2><div>{t.operators.map(([role,title,body])=><article key={role}><span>{role}</span><h3>{title.split("\n").map((line,index)=><>{line}{index === 0 && <br />}</>)}</h3><p>{body}</p></article>)}</div><a href="/dossier/read/mint-manifest">{t.manifest} ↗</a></section>
    <section className="launch-rule"><p>{t.rule}</p><h2>{t.ruleText}</h2><a href="/?activate=1">{t.terminal} →</a></section><footer>{t.footer}</footer>
  </main>;
}
