"use client";

import { useEffect, useState } from "react";

const content = {
  en: {
    lang: "TR", kicker: "INTERNAL AGENCY // CANONICAL DOSSIER", title: <>THE SIGNAL<br />IS OPEN.</>, intro: "A public record for STAR ASCENT: myth, mechanism, and the evidence required to make both real.", section1: "THE TRANSMISSION", thesis: "The future is not handed down. It is taken back.", body: "STAR ASCENT is the first public transmission of Internal Agency: a living experiment in collective imagination, technology, culture, and self-determination. We are here to build the strange, the beautiful, and the useful in public.", section2: "FIXED-SUPPLY PROTOCOL", supply: "1,000,000,000", supplyLabel: "IAT MAXIMUM SUPPLY", allocations: [["COMMUNITY", "50%", "500M"], ["TREASURY", "20%", "200M"], ["ECOSYSTEM", "15%", "150M"], ["CORE TEAM", "10%", "100M"], ["LIQUIDITY", "5%", "50M"]], section3: "THE LOCK IS THE MESSAGE", locks: [["TREASURY", "12-month cliff · 36-month linear release"], ["ECOSYSTEM", "6-month cliff · 24-month linear release"], ["CORE TEAM", "12-month cliff · 36-month linear release"], ["AUTHORITY", "Mint and freeze authority permanently revoked after the documented initial mint"]], associate: "ASSOCIATE DLC", associateBody: "Associate DLC arrives after genesis as a non-custodial affiliation and vouching layer. It is a social primitive, not a yield product. Any future incentive requires a separate public proposal with a funding source, formula, duration, governance path, and risks.", evidence: "GENESIS PROOF", evidenceBody: "Before any distribution: publish the mint, program, supply, authority-revocation evidence, allocation wallets, time-locks, and circulating-supply calculation. If any field is missing, the correct status is HOLD.", open: "OPEN THE SOURCE DOCUMENTS", whiteDossier: "White Dossier", tokenomics: "Tokenomics", proof: "Genesis proof record", boundary: "No presale. No paid registration. No promise of price, yield, APY, or return.", footer: "STAR ASCENT // BUILD WITH DISCERNMENT" },
  tr: {
    lang: "EN", kicker: "İLERİ AKIL // KANONİK DOSYA", title: <>SİNYAL<br />AÇIK.</>, intro: "STAR ASCENT için kamusal kayıt: mit, mekanizma ve ikisini de gerçek kılmak için gereken kanıt.", section1: "İLETİM", thesis: "Gelecek bahşedilmez. Geri alınır.", body: "STAR ASCENT, İleri Akıl'ın ilk kamusal iletimidir: kolektif hayal gücü, teknoloji, kültür ve öz-belirlenim üzerine yaşayan bir deney. Tuhafı, güzeli ve faydalıyı herkesin gözü önünde inşa etmek için buradayız.", section2: "SABİT ARZ PROTOKOLÜ", supply: "1.000.000.000", supplyLabel: "IAT AZAMİ ARZ", allocations: [["TOPLULUK", "%50", "500M"], ["HAZİNE", "%20", "200M"], ["EKOSİSTEM", "%15", "150M"], ["ÇEKİRDEK EKİP", "%10", "100M"], ["LİKİDİTE", "%5", "50M"]], section3: "KİLİT MESAJDIR", locks: [["HAZİNE", "12 ay cliff · 36 ay doğrusal serbest bırakma"], ["EKOSİSTEM", "6 ay cliff · 24 ay doğrusal serbest bırakma"], ["ÇEKİRDEK EKİP", "12 ay cliff · 36 ay doğrusal serbest bırakma"], ["YETKİ", "Belgelenmiş ilk mint işleminden sonra mint ve dondurma yetkileri kalıcı olarak kaldırılır"]], associate: "ASSOCIATE DLC", associateBody: "Associate DLC başlangıçtan sonra gözetimsiz bir bağlantı ve kefillik katmanı olarak gelir. Sosyal bir ilkedir; getiri ürünü değildir. Gelecekteki teşvik için fon kaynağı, formül, süre, yönetişim yolu ve riskleri içeren ayrı bir kamu önerisi gerekir.", evidence: "BAŞLANGIÇ KANITI", evidenceBody: "Herhangi bir dağıtımdan önce mint, program, arz, yetki kaldırma kanıtı, tahsis cüzdanları, zaman kilitleri ve dolaşımdaki arz hesabını yayımlayın. Herhangi bir alan eksikse doğru durum BEKLET'tir.", open: "KAYNAK BELGELERİ AÇ", whiteDossier: "Beyaz Dosya", tokenomics: "Tokenomics", proof: "Başlangıç kanıt kaydı", boundary: "Ön satış yok. Ücretli kayıt yok. Fiyat, getiri, APY veya kazanç vaadi yok.", footer: "STAR ASCENT // SAĞDUYU İLE İNŞA ET" },
};

const trClean = {
  lang: "EN", kicker: "İLERİ AKIL // KANONİK DOSYA", title: <>SİNYAL<br />AÇIK.</>, intro: "STAR ASCENT için kamusal kayıt: mit, mekanizma ve ikisini de gerçek kılmak için gereken kanıt.",
  section1: "İLETİM", thesis: "Gelecek bahşedilmez. Geri alınır.", body: "STAR ASCENT, İleri Akıl'ın ilk kamusal iletimidir: kolektif hayal gücü, teknoloji, kültür ve öz-belirlenim üzerine yaşayan bir deney. Tuhafı, güzeli ve faydalıyı herkesin gözü önünde inşa etmek için buradayız.",
  section2: "SABİT ARZ PROTOKOLÜ", supply: "1.000.000.000", supplyLabel: "IAT AZAMİ ARZ", allocations: [["TOPLULUK", "%50", "500M"], ["HAZİNE", "%20", "200M"], ["EKOSİSTEM", "%15", "150M"], ["ÇEKİRDEK EKİP", "%10", "100M"], ["LİKİDİTE", "%5", "50M"]],
  section3: "KİLİT MESAJDIR", locks: [["HAZİNE", "12 ay cliff · 36 ay doğrusal serbest bırakma"], ["EKOSİSTEM", "6 ay cliff · 24 ay doğrusal serbest bırakma"], ["ÇEKİRDEK EKİP", "12 ay cliff · 36 ay doğrusal serbest bırakma"], ["YETKİ", "Belgelenmiş ilk mint işleminden sonra mint ve dondurma yetkileri kalıcı olarak kaldırılır"]],
  associate: "ASSOCIATE DLC", associateBody: "Associate DLC başlangıçtan sonra gözetimsiz bir bağlantı ve kefillik katmanı olarak gelir. Sosyal bir ilkedir; getiri ürünü değildir. Gelecekteki teşvik için fon kaynağı, formül, süre, yönetişim yolu ve riskleri içeren ayrı bir kamu önerisi gerekir.",
  evidence: "BAŞLANGIÇ KANITI", evidenceBody: "Herhangi bir dağıtımdan önce mint, program, arz, yetki kaldırma kanıtı, tahsis cüzdanları, zaman kilitleri ve dolaşımdaki arz hesabını yayımlayın. Herhangi bir alan eksikse doğru durum BEKLET'tir.",
  open: "KAYNAK BELGELERİ AÇ", whiteDossier: "Beyaz Dosya", tokenomics: "Tokenomics", proof: "Başlangıç kanıt kaydı", boundary: "Ön satış yok. Ücretli kayıt yok. Fiyat, getiri, APY veya kazanç vaadi yok.", footer: "STAR ASCENT // SAĞDUYU İLE İNŞA ET"
};

export default function DossierPage() {
  const [language, setLanguage] = useState<"en" | "tr">("en");
  useEffect(() => { if (window.location.hostname.includes("ileriakil")) setLanguage("tr"); }, []);
  const t = language === "tr" ? trClean : content.en;
  const proposedLocks = t.locks.map(([label, detail]) => [label, `${language === "en" ? "Proposed: " : "ONERI: "}${detail}`]);
  const lockHeading = language === "en" ? "THE LOCK IS THE MESSAGE // PROPOSED" : "KILIT MESAJDIR // ONERI";
  return <main className="dossier-page">
    <div className="dossier-stars" aria-hidden="true" />
    <nav className="dossier-nav"><a href="/">IA<span>///</span></a><div><a className="dossier-signal-link" href="/signal">{language === "en" ? "SIGNAL" : "SİNYAL"}</a><button onClick={() => setLanguage(language === "en" ? "tr" : "en")}>{t.lang}</button></div></nav>
    <section className="dossier-hero"><p>{t.kicker}</p><h1>{t.title}</h1><div className="dossier-orbit" aria-hidden="true"><i /><i /><i /></div><p className="dossier-intro">{t.intro}</p><div className="dossier-live-strip" aria-label={language === "en" ? "Live archive status" : "Canlı arşiv durumu"}><span><b>●</b> {language === "en" ? "ARCHIVE LIVE" : "ARŞİV CANLI"}</span><span>{language === "en" ? "OUTER COMMS: SECURE" : "DIŞ İLETİŞİM: GÜVENLİ"}</span><span>{language === "en" ? "SIGNAL: RISING" : "SİNYAL: YÜKSELİYOR"}</span></div><nav className="dossier-chapters" aria-label={language === "en" ? "Dossier chapters" : "Dosya bölümleri"}><a href="#transmission">01 / {language === "en" ? "SIGNAL" : "SİNYAL"}</a><a href="#tokenomics">02 / TOKENOMICS</a><a href="#locks">03 / {language === "en" ? "LOCKS" : "KİLİTLER"}</a><a href="#records">04 / {language === "en" ? "RECORDS" : "KAYITLAR"}</a></nav></section>
    <figure className="story-art"><img src="/images/stage-manager-story.png" alt={language === "en" ? "The STAR ASCENT stage manager on the ship bridge, with AI light operators conducting a cosmic rave" : "Yıldız gemisi köprüsündeki STAR ASCENT sahne yöneticisi ve kozmik rave'i yöneten yapay zekâ ışık operatörleri"} /><figcaption>{language === "en" ? "THE STAGE MANAGER // THE SHIP IS A SIGNAL" : "SAHNE YÖNETİCİSİ // GEMİ BİR SİNYALDİR"}</figcaption></figure>
    <section className="dossier-thesis" id="transmission"><p>{t.section1}</p><h2>{t.thesis}</h2><p>{t.body}</p></section>
    <section className="dossier-tokenomics" id="tokenomics"><p>{t.section2}</p><div className="supply-mark"><strong>{t.supply}</strong><span>{t.supplyLabel}</span></div><div className="allocation-table">{t.allocations.map(([name, share, amount]) => <div key={name}><i aria-hidden="true" style={{ width: `${share.replace("%", "")}%` }} /><b>{name}</b><span>{share}</span><strong>{amount}</strong></div>)}</div></section>
    <section className="dossier-locks" id="locks"><p>{lockHeading}</p><div>{proposedLocks.map(([label, detail], index) => <article key={label}><span>0{index + 1}</span><h3>{label}</h3><p>{detail}</p></article>)}</div></section>
    <figure className="dossier-crew-art"><img src="/images/scorpion-commander-portrait-v1.png" alt={language === "en" ? "Adult STAR ASCENT commander with the launch crew in the red-light control deck" : "Kırmızı ışıklı kontrol güvertesinde yetişkin STAR ASCENT komutanı ve fırlatma ekibi"} /><figcaption>{language === "en" ? "THE CREW IS THE CONSTELLATION // LIVE BUILD" : "EKİP TAKIMYILDIZIDIR // CANLI YAPI"}</figcaption></figure>
    <section className="dossier-duo"><article><p>{t.associate}</p><h2>{t.associateBody}</h2></article><article><p>{t.evidence}</p><h2>{t.evidenceBody}</h2></article></section>
    <section className="dossier-sources" id="records"><p>{t.open}</p><div><a href="/dossier/read/white-dossier">{t.whiteDossier}</a><a href="/dossier/read/tokenomics">{t.tokenomics}</a><a href="/dossier/read/genesis-proof">{t.proof}</a></div><small>{t.boundary}</small></section>
    <footer>{t.footer}</footer>
  </main>;
}
