"use client";

import { useEffect, useState } from "react";

const content = {
  en: {
    lang: "TR", kicker: "INTERNAL AGENCY // CANONICAL DOSSIER", title: <>THE SIGNAL<br />IS OPEN.</>, intro: "A public record for STAR ASCENT: myth, mechanism, and the evidence required to make both real.",
    section1: "THE TRANSMISSION", thesis: "The future is not handed down. It is taken back.", body: "STAR ASCENT is the first public transmission of Internal Agency: a living experiment in collective imagination, technology, culture, and self-determination. We are here to build the strange, the beautiful, and the useful in public.",
    section2: "FIXED-SUPPLY PROTOCOL", supply: "1,000,000,000", supplyLabel: "IAT MAXIMUM SUPPLY", allocations: [["COMMUNITY", "50%", "500M"], ["TREASURY", "20%", "200M"], ["ECOSYSTEM", "15%", "150M"], ["CORE TEAM", "10%", "100M"], ["LIQUIDITY", "5%", "50M"]],
    locks: [["TREASURY REWARD LANE", "25% available at Genesis target; remaining 75% has a 12-month cliff, then 36-month linear release"], ["ECOSYSTEM REWARD LANE", "25% available at Genesis target; remaining 75% has a 6-month cliff, then 24-month linear release"], ["LIQUIDITY REWARD LANE", "25% available at Genesis target; remaining 75% has a 6-month cliff, then linear release through month 24"], ["CORE TEAM", "100M principal: 6-month cliff, then linear through month 24; fixed 17% annual reward rate across the full principal while vesting"], ["AUTHORITY", "Mint and freeze authority permanently revoked after the documented initial mint"]],
    associate: "REWARD + CCC POLICY", associateBody: "The proposed staking system uses simple annual reward rates paid weekly without automatic compounding: standard user 10%, CCC Agent 28%, eligible downstream CCC associate 20%, and core team 17%. A public random draw reassigns one CCC Agency every week and pauses that Agency and its snapshotted downstream group for the turn. Every exact protocol tie uses the same final one-roll, exact-uniform, publicly verifiable method. The program is not active.",
    evidence: "GENESIS PROOF", evidenceBody: "Before any distribution: publish the mint, program, supply, authority-revocation evidence, allocation wallets, program vaults, time-locks, circulating-supply calculation, and reward-contract review. If any field is missing, the correct status is HOLD.",
    open: "OPEN THE SOURCE DOCUMENTS", whiteDossier: "White Dossier", tokenomics: "Tokenomics", policy: "Economic policy V2", proof: "Genesis proof record", boundary: "No presale. No token-price, profit, or guaranteed market-value promise. Reward contracts and mainnet remain on HOLD until implementation and evidence are public.", footer: "STAR ASCENT // BUILD WITH DISCERNMENT",
  },
  tr: {
    lang: "EN", kicker: "İLERİ AKIL // KANONİK DOSYA", title: <>SİNYAL<br />AÇIK.</>, intro: "STAR ASCENT için kamusal kayıt: mit, mekanizma ve ikisini de gerçek kılmak için gereken kanıt.",
    section1: "İLETİM", thesis: "Gelecek bahşedilmez. Geri alınır.", body: "STAR ASCENT, İleri Akıl'ın ilk kamusal iletimidir: kolektif hayal gücü, teknoloji, kültür ve öz-belirlenim üzerine yaşayan bir deney. Tuhafı, güzeli ve faydalıyı herkesin gözü önünde inşa etmek için buradayız.",
    section2: "SABİT ARZ PROTOKOLÜ", supply: "1.000.000.000", supplyLabel: "IAT AZAMİ ARZ", allocations: [["TOPLULUK", "%50", "500M"], ["HAZİNE", "%20", "200M"], ["EKOSİSTEM", "%15", "150M"], ["ÇEKİRDEK EKİP", "%10", "100M"], ["LİKİDİTE", "%5", "50M"]],
    locks: [["HAZİNE ÖDÜL HATTI", "Başlangıç hedefinde %25 kullanılabilir; kalan %75 için 12 ay cliff ve ardından 36 ay doğrusal serbest bırakma"], ["EKOSİSTEM ÖDÜL HATTI", "Başlangıç hedefinde %25 kullanılabilir; kalan %75 için 6 ay cliff ve ardından 24 ay doğrusal serbest bırakma"], ["LİKİDİTE ÖDÜL HATTI", "Başlangıç hedefinde %25 kullanılabilir; kalan %75 için 6 ay cliff ve ardından 24. aya kadar doğrusal serbest bırakma"], ["ÇEKİRDEK EKİP", "100M anapara: 6 ay cliff, ardından 24. aya kadar doğrusal serbest bırakma; hak ediş sırasında anaparanın tamamına sabit %17 yıllık ödül oranı"], ["YETKİ", "Belgelenmiş ilk mint işleminden sonra mint ve dondurma yetkileri kalıcı olarak kaldırılır"]],
    associate: "ÖDÜL + CCC POLİTİKASI", associateBody: "Önerilen staking sistemi otomatik bileşik olmayan ve haftalık ödenen basit yıllık ödül oranları kullanır: standart kullanıcı %10, CCC Agent %28, uygun alt CCC associate %20 ve çekirdek ekip %17. Kamusal rastgele çekiliş her hafta bir CCC Agency konumunu yeniden atar ve o Agency ile anlık görüntüdeki alt grubunu bir tur duraklatır. Her tam protokol eşitliği aynı kesin, tek çekilişli, tam eşit dağılımlı ve kamuya açık doğrulanabilir yöntemle çözülür. Program aktif değildir.",
    evidence: "BAŞLANGIÇ KANITI", evidenceBody: "Herhangi bir dağıtımdan önce mint, program, arz, yetki kaldırma kanıtı, tahsis cüzdanları, program kasaları, zaman kilitleri, dolaşımdaki arz hesabı ve ödül sözleşmesi incelemesini yayımlayın. Herhangi bir alan eksikse doğru durum BEKLET'tir.",
    open: "KAYNAK BELGELERİ AÇ", whiteDossier: "Beyaz Dosya", tokenomics: "Tokenomics", policy: "Ekonomi politikası V2", proof: "Başlangıç kanıt kaydı", boundary: "Ön satış yok. Token fiyatı, kâr veya garantili piyasa değeri vaadi yok. Uygulama ve kanıt kamusal olana kadar ödül sözleşmeleri ve mainnet BEKLET durumundadır.", footer: "STAR ASCENT // SAĞDUYU İLE İNŞA ET",
  },
};

export default function DossierPage() {
  const [language, setLanguage] = useState<"en" | "tr">("en");
  useEffect(() => { if (window.location.hostname.includes("ileriakil")) setLanguage("tr"); }, []);
  const t = content[language];
  const proposedLocks = t.locks.map(([label, detail]) => [label, `${language === "en" ? "Proposed: " : "ÖNERİ: "}${detail}`]);
  const lockHeading = language === "en" ? "THE LOCK IS THE MESSAGE // PROPOSED" : "KİLİT MESAJDIR // ÖNERİ";

  return <main className="dossier-page">
    <div className="dossier-stars" aria-hidden="true" />
    <nav className="dossier-nav"><a href="/">IA<span>///</span></a><div><a className="dossier-signal-link" href="/signal">{language === "en" ? "SIGNAL" : "SİNYAL"}</a><button onClick={() => setLanguage(language === "en" ? "tr" : "en")}>{t.lang}</button></div></nav>
    <section className="dossier-hero"><p>{t.kicker}</p><h1>{t.title}</h1><div className="dossier-orbit" aria-hidden="true"><i /><i /><i /></div><p className="dossier-intro">{t.intro}</p><div className="dossier-live-strip" role="status" aria-label={language === "en" ? "Live archive status" : "Canlı arşiv durumu"}><span><b>●</b> {language === "en" ? "ARCHIVE LIVE" : "ARŞİV CANLI"}</span><span>{language === "en" ? "REWARD CONTRACT: HOLD" : "ÖDÜL SÖZLEŞMESİ: BEKLET"}</span><span>{language === "en" ? "MAINNET: HOLD" : "MAINNET: BEKLET"}</span></div><nav className="dossier-chapters" aria-label={language === "en" ? "Dossier chapters" : "Dosya bölümleri"}><a href="#transmission">01 / {language === "en" ? "SIGNAL" : "SİNYAL"}</a><a href="#tokenomics">02 / TOKENOMICS</a><a href="#locks">03 / {language === "en" ? "LOCKS" : "KİLİTLER"}</a><a href="#records">04 / {language === "en" ? "RECORDS" : "KAYITLAR"}</a></nav></section>
    <figure className="story-art"><img src="/images/stage-manager-story.webp" alt={language === "en" ? "The STAR ASCENT stage manager on the ship bridge, with AI light operators conducting a cosmic rave" : "Yıldız gemisi köprüsündeki STAR ASCENT sahne yöneticisi ve kozmik rave'i yöneten yapay zekâ ışık operatörleri"} /><figcaption>{language === "en" ? "THE STAGE MANAGER // THE SHIP IS A SIGNAL" : "SAHNE YÖNETİCİSİ // GEMİ BİR SİNYALDİR"}</figcaption></figure>
    <section className="dossier-thesis" id="transmission"><p>{t.section1}</p><h2>{t.thesis}</h2><p>{t.body}</p></section>
    <section className="dossier-tokenomics" id="tokenomics"><p>{t.section2}</p><div className="supply-mark"><strong>{t.supply}</strong><span>{t.supplyLabel}</span></div><div className="allocation-table">{t.allocations.map(([name, share, amount]) => <div key={name}><i aria-hidden="true" style={{ width: `${share.replace("%", "")}%` }} /><b>{name}</b><span>{share}</span><strong>{amount}</strong></div>)}</div></section>
    <section className="dossier-locks" id="locks"><p>{lockHeading}</p><div>{proposedLocks.map(([label, detail], index) => <article key={label}><span>0{index + 1}</span><h3>{label}</h3><p>{detail}</p></article>)}</div></section>
    <figure className="dossier-crew-art"><img src="/images/scorpion-commander-portrait-v1.webp" alt={language === "en" ? "Adult STAR ASCENT commander with the launch crew in the red-light control deck" : "Kırmızı ışıklı kontrol güvertesinde yetişkin STAR ASCENT komutanı ve fırlatma ekibi"} /><figcaption>{language === "en" ? "THE CREW IS THE CONSTELLATION // LIVE BUILD" : "EKİP TAKIMYILDIZIDIR // CANLI YAPI"}</figcaption></figure>
    <section className="dossier-duo"><article><p>{t.associate}</p><h2>{t.associateBody}</h2></article><article><p>{t.evidence}</p><h2>{t.evidenceBody}</h2></article></section>
    <section className="dossier-sources" id="records"><p>{t.open}</p><div><a href="/tokenomics">{t.policy}</a><a href="/dossier/read/white-dossier">{t.whiteDossier}</a><a href="/dossier/read/tokenomics">{t.tokenomics}</a><a href="/dossier/read/genesis-proof">{t.proof}</a></div><small>{t.boundary}</small></section>
    <footer>{t.footer}</footer>
  </main>;
}
